[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "*.js"
  [headers.values]
  Cache-Control = "public, max-age=604800, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
  Cache-Control = "public, max-age=604800, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
  Cache-Control = "public, max-age=604800, immutable"